name: BossbarCountdown
version: 1.2
description: Countdown as Bossbar and perform action when finished
authors: [Kirastur]
website: https://www.spigotmc.org/resources/bossbarcountdown.94169

api-version: 1.19
load: POSTWORLD
main: de.polarwolf.bbcd.main.Main

commands:
    bbcd:
        description: Admin-Commands for BossbarCountdown Plugin
        permission: hotblocks.admin
        usage: "Query a list of valid subcommands by using: /bbcd help"

permissions:
    bbcd.admn:
        description: Can use the BossbarCountdown Admin-Command
        default: op
